# Generated by Django 3.2.5 on 2022-11-28 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Authentication', '0004_auto_20221127_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userprofilemodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='App_Authentication.userprofilemodel'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='App_Authentication.userprofilemodel'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='discription',
            field=models.TextField(max_length=300),
        ),
    ]
