# Generated by Django 3.2.5 on 2022-11-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Authentication', '0006_auto_20221128_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='facebook_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='instagram_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='linkedin_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='twitter_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
